//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationA2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Login
    {
        public int LoginId { get; set; }

        [Required(ErrorMessage = "Please Provide Username!", AllowEmptyStrings = false)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Please Provide Password!", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string PassWord { get; set; }

        [Compare("PassWord", ErrorMessage = "Password's do not match!")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public String ConfirmPassWord { get; set; }

        [Required(ErrorMessage = "Please Provide a Name!", AllowEmptyStrings = false)]
        public string Name { get; set; }
    }
}
