//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplicationA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidOrder
    {
        public int PaidOrderId { get; set; }
        public string CustomerId { get; set; }
        public string ProductTitle { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
    }
}
